/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Collection;
import java.util.Collections;
import java.util.List;
import static javafx.scene.input.KeyCode.T;

/**
 *
 * @author luisdiegomontealegrebadilla
 */
public class List_People extends javax.swing.JFrame {

    public static final String URL = "jdbc:sqlserver://localhost:1433; database = Proyecto_Progra";
    public static final String Username = "Admin";
    public static final String Password = "Proyecto";

    PreparedStatement ps;
    ResultSet rs;

    /**
     * Creates new form List_People
     */
    public List_People() {
        initComponents();
        cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_lista = new javax.swing.JTable();
        exit_btn = new javax.swing.JButton();
        Separator_2 = new javax.swing.JSeparator();
        Separator_1 = new javax.swing.JSeparator();
        usrs_message = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_lista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identificacion", "Nombre", "Primer Apellido", "Segundo Apellido", "Carrera Universitaria", "Estado Civil", "País", "Dirección", "Fecha de Nacimiento", "Edad", "Universidad", "Teléfono", "Correo Eléctronico", "Estado", "Observaciones"
            }
        ));
        jScrollPane1.setViewportView(tbl_lista);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 970, 180));

        exit_btn.setBackground(new java.awt.Color(102, 204, 255));
        exit_btn.setForeground(new java.awt.Color(255, 255, 255));
        exit_btn.setText("Salir");
        exit_btn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 204, 255), new java.awt.Color(51, 204, 255), java.awt.Color.white, new java.awt.Color(51, 204, 255)));
        exit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_btnActionPerformed(evt);
            }
        });
        getContentPane().add(exit_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 490, 100, 30));

        Separator_2.setBackground(new java.awt.Color(0, 0, 0));
        Separator_2.setForeground(new java.awt.Color(0, 204, 255));
        getContentPane().add(Separator_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 960, 20));

        Separator_1.setBackground(new java.awt.Color(0, 0, 0));
        Separator_1.setForeground(new java.awt.Color(0, 204, 255));
        getContentPane().add(Separator_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 970, 20));

        usrs_message.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        usrs_message.setText("Lista de personas");
        getContentPane().add(usrs_message, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 340, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/onu_scholarship_sys/1200px-Flag_of_the_United_Nations.svg.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(-130, 0, 1120, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_btnActionPerformed
        this.dispose();
        call_menu();
    }//GEN-LAST:event_exit_btnActionPerformed

    // declaracion de metodos para llamado de formularios
    private void call_menu() {

        Main_Menu menu_principal = new Main_Menu();
        menu_principal.setTitle("Menu Principal");
        menu_principal.setTitle("Menu Principal");
        menu_principal.setSize(900, 600);
        menu_principal.setLocationRelativeTo(null);
        menu_principal.setVisible(true);

    }

    private void cargarTabla() {

        DefaultTableModel modeloTabla = (DefaultTableModel) tbl_lista.getModel();

        modeloTabla.setRowCount(0);

        PreparedStatement ps;
        ResultSet rs;
        ResultSetMetaData rsmd;
        int columnas;

        try {
            Connection con = Conexion.getConnection();
            ps = con.prepareStatement("Select ID, Nombre, Apellido1, Apellido2, Carrera, Estado_Civil, Pais, Direccion, Fecha_Nacimiento, Edad, Universidad, Telefono, Correo_Electronico, Estado, Observaciones  From Estudiante");

            rs = ps.executeQuery();
            rsmd = rs.getMetaData();

            columnas = rsmd.getColumnCount();

            while (rs.next()) {

                Object[] fila = new Object[columnas];

                for (int indice = 0; indice < columnas; indice++) {
                    fila[indice] = rs.getObject(indice + 1);
                }

                modeloTabla.addRow(fila);
            }

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, e.toString());
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look abackground setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(List_People.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(List_People.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(List_People.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(List_People.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new List_People().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator Separator_1;
    private javax.swing.JSeparator Separator_2;
    private javax.swing.JLabel background;
    private javax.swing.JButton exit_btn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_lista;
    private javax.swing.JLabel usrs_message;
    // End of variables declaration//GEN-END:variables
}
