/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author luisdiegomontealegrebadilla
 */
public class Main_Menu extends javax.swing.JFrame {

    /**
     * Creates new form Main_Menu
     */
    public Main_Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CopyRight = new javax.swing.JLabel();
        Separator_2 = new javax.swing.JSeparator();
        about_sys = new javax.swing.JButton();
        Separator_1 = new javax.swing.JSeparator();
        background = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        add_person_box = new javax.swing.JCheckBoxMenuItem();
        add_user_box = new javax.swing.JCheckBoxMenuItem();
        list_people_checkbox = new javax.swing.JCheckBoxMenuItem();
        list_countries_box = new javax.swing.JCheckBoxMenuItem();
        exit_checkbox = new javax.swing.JCheckBoxMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CopyRight.setForeground(new java.awt.Color(51, 51, 51));
        CopyRight.setText("Todos los derechos reservados - 2021 ©");
        getContentPane().add(CopyRight, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 470, 270, 60));

        Separator_2.setBackground(new java.awt.Color(0, 0, 0));
        Separator_2.setForeground(new java.awt.Color(0, 204, 255));
        getContentPane().add(Separator_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 940, 30));

        about_sys.setText("Acerca del Sistema");
        about_sys.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                about_sysActionPerformed(evt);
            }
        });
        getContentPane().add(about_sys, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 490, 150, -1));

        Separator_1.setBackground(new java.awt.Color(0, 0, 0));
        Separator_1.setForeground(new java.awt.Color(0, 204, 255));
        getContentPane().add(Separator_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 940, 30));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/onu_scholarship_sys/1200px-Flag_of_the_United_Nations.svg.png"))); // NOI18N
        background.setFocusable(false);
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(-140, 0, 1080, 540));

        jMenu1.setText("Archivo");
        jMenu1.setToolTipText("");

        add_person_box.setSelected(true);
        add_person_box.setText("Agregar Persona");
        add_person_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_person_boxActionPerformed(evt);
            }
        });
        jMenu1.add(add_person_box);

        add_user_box.setSelected(true);
        add_user_box.setText("Agregar Usuario");
        add_user_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_user_boxActionPerformed(evt);
            }
        });
        jMenu1.add(add_user_box);

        list_people_checkbox.setSelected(true);
        list_people_checkbox.setText("Listar Personas");
        list_people_checkbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list_people_checkboxActionPerformed(evt);
            }
        });
        jMenu1.add(list_people_checkbox);

        list_countries_box.setSelected(true);
        list_countries_box.setText("Listar paises");
        list_countries_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list_countries_boxActionPerformed(evt);
            }
        });
        jMenu1.add(list_countries_box);

        exit_checkbox.setSelected(true);
        exit_checkbox.setText("Salir");
        exit_checkbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_checkboxActionPerformed(evt);
            }
        });
        jMenu1.add(exit_checkbox);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ayuda");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void about_sysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_about_sysActionPerformed
        this.dispose();
        call_about_sys();
    }//GEN-LAST:event_about_sysActionPerformed

    private void add_person_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_person_boxActionPerformed
        this.dispose();
        try {
            call_new_student();
        } catch (IOException ex) {
            Logger.getLogger(Main_Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_add_person_boxActionPerformed

    private void exit_checkboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_checkboxActionPerformed
        this.dispose();
        call_login();
    }//GEN-LAST:event_exit_checkboxActionPerformed

    private void list_people_checkboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list_people_checkboxActionPerformed
        this.dispose();
        call_list_people();
    }//GEN-LAST:event_list_people_checkboxActionPerformed

    private void list_countries_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list_countries_boxActionPerformed
        this.dispose();
        call_countries();
    }//GEN-LAST:event_list_countries_boxActionPerformed

    private void add_user_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_user_boxActionPerformed
        this.dispose();
        try {
            call_new_user();
        } catch (IOException ex) {
            Logger.getLogger(Main_Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_add_user_boxActionPerformed

    // declaracion de metodos para llamado de formularios
    private void call_countries() {
        Country_list paises = new Country_list();
        paises.setTitle("Lista de Paises");
        paises.setSize(920, 560);
        paises.setLocationRelativeTo(null);
        paises.setVisible(true);

    }

    private void call_login() {
        Login inicio = new Login();
        inicio.setTitle("Menu Principal");
        inicio.setSize(939, 550);
        inicio.setLocationRelativeTo(null);
        inicio.setVisible(true);

    }

    private void call_list_people() {
        List_People listar_personas = new List_People();
        listar_personas.setTitle("Lista de personas");
        listar_personas.setSize(950, 640);
        listar_personas.setLocationRelativeTo(null);
        listar_personas.setVisible(true);

    }

    private void call_new_student() throws IOException {
        New_Student nuevo_estudiante = new New_Student();
        nuevo_estudiante.setTitle("Nuevo Estudiante");
        nuevo_estudiante.setSize(1080, 590);
        nuevo_estudiante.setLocationRelativeTo(null);
        nuevo_estudiante.setVisible(true);
    }

    private void call_new_user() throws IOException {
        New_User nuevo_user = new New_User();
        nuevo_user.setTitle("Nuevo Usuario");
        nuevo_user.setSize(1080, 590);
        nuevo_user.setLocationRelativeTo(null);
        nuevo_user.setVisible(true);
    }

    private void call_about_sys() {
        about_sys sobre = new about_sys();
        sobre.setTitle("Acerca de");
        sobre.setSize(920, 550);
        sobre.setLocationRelativeTo(null);
        sobre.setVisible(true);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CopyRight;
    private javax.swing.JSeparator Separator_1;
    private javax.swing.JSeparator Separator_2;
    private javax.swing.JButton about_sys;
    private javax.swing.JCheckBoxMenuItem add_person_box;
    private javax.swing.JCheckBoxMenuItem add_user_box;
    private javax.swing.JLabel background;
    private javax.swing.JCheckBoxMenuItem exit_checkbox;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JCheckBoxMenuItem list_countries_box;
    private javax.swing.JCheckBoxMenuItem list_people_checkbox;
    // End of variables declaration//GEN-END:variables
}
