/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.json.JSONArray;
import org.json.JSONObject;

/**
 *
 * @author luisdiegomontealegrebadilla
 */
public class New_Student extends javax.swing.JFrame {

    public static final String URL = "jdbc:sqlserver://localhost:1433; database = Proyecto_Progra";
    public static final String Username = "Admin";
    public static final String Password = "Proyecto";

    PreparedStatement ps;
    ResultSet rs;

    public static Connection getConnection() throws ClassNotFoundException {

        String conexionURL = "jdbc:sqlserver://localhost:1433;"
                + "database = Proyecto_Progra;"
                + "user = Admin;"
                + "password = Proyecto;"
                + "loginTimeout = 45;";

        try {

            Connection con = DriverManager.getConnection(conexionURL);
            return con;

        } catch (SQLException ex) {
            System.out.println(ex.toString());
            return null;
        }

    }

    private void limpiarcajas() {

        txt_id.setText(null);
        txt_nombre.setText(null);
        txt_ap1.setText(null);
        txt_ap2.setText(null);
        cb_carrera.setSelectedIndex(0);
        cb_estado_civil.setSelectedIndex(0);
        cb_pais.setSelectedIndex(0);
        txt_direccion.setText(null);
        txt_fnacimiento.setText(null);
        txt_edad.setText(null);
        txt_universidad.setText(null);
        txt_telefono.setText(null);
        txt_correo.setText(null);
        cb_estado.setSelectedIndex(0);
        txt_observaciones.setText(null);

    }

    public New_Student() throws IOException {
        initComponents();

        txt_id2.setVisible(false);

        poblar_lista_paises();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        est_reg_label = new javax.swing.JLabel();
        Major_label = new javax.swing.JLabel();
        Separator_1 = new javax.swing.JSeparator();
        cb_carrera = new javax.swing.JComboBox<>();
        Civil_State_label = new javax.swing.JLabel();
        cb_estado_civil = new javax.swing.JComboBox<>();
        Civil_State_label1 = new javax.swing.JLabel();
        txt_fnacimiento = new javax.swing.JTextField();
        address_label = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_direccion = new javax.swing.JTextArea();
        college_label = new javax.swing.JLabel();
        txt_universidad = new javax.swing.JTextField();
        email_label = new javax.swing.JLabel();
        txt_correo = new javax.swing.JTextField();
        current_state_label = new javax.swing.JLabel();
        cb_estado = new javax.swing.JComboBox<>();
        observations_label = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_observaciones = new javax.swing.JTextArea();
        Separator_2 = new javax.swing.JSeparator();
        Back_button = new javax.swing.JButton();
        btn_buscar = new javax.swing.JButton();
        btn_modificar = new javax.swing.JButton();
        CopyRight = new javax.swing.JLabel();
        Name_label = new javax.swing.JLabel();
        lastname_label1 = new javax.swing.JLabel();
        lastname_label2 = new javax.swing.JLabel();
        ID_label = new javax.swing.JLabel();
        tel_label = new javax.swing.JLabel();
        Country_label = new javax.swing.JLabel();
        age_label = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        txt_id = new javax.swing.JTextField();
        txt_ap1 = new javax.swing.JTextField();
        txt_ap2 = new javax.swing.JTextField();
        txt_telefono = new javax.swing.JTextField();
        cb_pais = new javax.swing.JComboBox<>();
        txt_edad = new javax.swing.JTextField();
        btn_agregar1 = new javax.swing.JButton();
        btn_limpiar = new javax.swing.JButton();
        btn_borrar = new javax.swing.JButton();
        background = new javax.swing.JLabel();
        txt_id2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        est_reg_label.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        est_reg_label.setText("Registro de Estudiante");
        getContentPane().add(est_reg_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 310, 30));

        Major_label.setText("Seleccione la carrera en curso");
        getContentPane().add(Major_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 200, 20));

        Separator_1.setBackground(new java.awt.Color(0, 0, 0));
        Separator_1.setForeground(new java.awt.Color(0, 204, 255));
        getContentPane().add(Separator_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1110, 20));

        cb_carrera.setBackground(new java.awt.Color(102, 204, 255));
        cb_carrera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Admin. en empresas", "Ing. Informatica", "Ing. en sistemas", "Ing. en software", "Ing. Quimica", "Medicina", "Filosofia", "Bach. en ingles" }));
        cb_carrera.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 204, 255), new java.awt.Color(51, 204, 255), java.awt.Color.white, new java.awt.Color(51, 204, 255)));
        cb_carrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_carreraActionPerformed(evt);
            }
        });
        getContentPane().add(cb_carrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 170, -1));

        Civil_State_label.setText("Estado Civil");
        getContentPane().add(Civil_State_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 200, 20));

        cb_estado_civil.setBackground(new java.awt.Color(102, 204, 255));
        cb_estado_civil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Soltero (a)", "Casado (a)", "Divorciado (a)", "Viudo (a)", "Union Libre" }));
        cb_estado_civil.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 204, 255), new java.awt.Color(51, 204, 255), java.awt.Color.white, new java.awt.Color(51, 204, 255)));
        cb_estado_civil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_estado_civilActionPerformed(evt);
            }
        });
        getContentPane().add(cb_estado_civil, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 170, -1));

        Civil_State_label1.setText("Fecha de Nacimiento (DD/MM/YYYY)");
        getContentPane().add(Civil_State_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 240, 20));

        txt_fnacimiento.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 204, 255), new java.awt.Color(51, 204, 255), null, new java.awt.Color(51, 204, 255)));
        txt_fnacimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_fnacimientoActionPerformed(evt);
            }
        });
        txt_fnacimiento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_fnacimientoKeyTyped(evt);
            }
        });
        getContentPane().add(txt_fnacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 170, -1));

        address_label.setText("Direccion de residencia:");
        getContentPane().add(address_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 240, 20));

        txt_direccion.setColumns(20);
        txt_direccion.setRows(5);
        txt_direccion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 204, 255), new java.awt.Color(51, 204, 255), java.awt.Color.white, new java.awt.Color(51, 204, 255)));
        txt_direccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_direccionKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(txt_direccion);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 170, 100));

        college_label.setText("Universidad Actual");
        getContentPane().add(college_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, 180, 20));

        txt_universidad.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 204, 255), new java.awt.Color(51, 204, 255), null, new java.awt.Color(51, 204, 255)));
        txt_universidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_universidadActionPerformed(evt);
            }
        });
        txt_universidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_universidadKeyTyped(evt);
            }
        });
        getContentPane().add(txt_universidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 170, -1));

        email_label.setText("Correo Electronico");
        getContentPane().add(email_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, 190, 20));

        txt_correo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 204, 255), new java.awt.Color(51, 204, 255), null, new java.awt.Color(51, 204, 255)));
        txt_correo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_correoActionPerformed(evt);
            }
        });
        txt_correo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_correoKeyTyped(evt);
            }
        });
        getContentPane().add(txt_correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, 170, -1));

        current_state_label.setText("Estado:");
        getContentPane().add(current_state_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, 240, 20));

        cb_estado.setBackground(new java.awt.Color(102, 204, 255));
        cb_estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Activo", "Inactivo" }));
        cb_estado.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 204, 255), new java.awt.Color(51, 204, 255), java.awt.Color.white, new java.awt.Color(51, 204, 255)));
        getContentPane().add(cb_estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 460, 170, -1));

        observations_label.setText("Observaciones:");
        getContentPane().add(observations_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 60, 240, 20));

        txt_observaciones.setColumns(20);
        txt_observaciones.setRows(5);
        txt_observaciones.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 204, 255), new java.awt.Color(51, 204, 255), java.awt.Color.white, new java.awt.Color(51, 204, 255)));
        jScrollPane2.setViewportView(txt_observaciones);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 90, -1, -1));

        Separator_2.setBackground(new java.awt.Color(0, 0, 0));
        Separator_2.setForeground(new java.awt.Color(0, 204, 255));
        getContentPane().add(Separator_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 1110, 20));

        Back_button.setBackground(new java.awt.Color(102, 204, 255));
        Back_button.setForeground(new java.awt.Color(255, 255, 255));
        Back_button.setText("Volver al Menú Principal");
        Back_button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 204, 255), new java.awt.Color(51, 204, 255), java.awt.Color.white, new java.awt.Color(51, 204, 255)));
        Back_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(Back_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 10, 150, 30));

        btn_buscar.setBackground(new java.awt.Color(102, 204, 255));
        btn_buscar.setForeground(new java.awt.Color(255, 255, 255));
        btn_buscar.setText("Buscar");
        btn_buscar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 204, 255), new java.awt.Color(51, 204, 255), java.awt.Color.white, new java.awt.Color(51, 204, 255)));
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 460, 100, 30));

        btn_modificar.setBackground(new java.awt.Color(102, 204, 255));
        btn_modificar.setForeground(new java.awt.Color(255, 255, 255));
        btn_modificar.setText("Modificar");
        btn_modificar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 204, 255), new java.awt.Color(51, 204, 255), java.awt.Color.white, new java.awt.Color(51, 204, 255)));
        btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 460, 100, 30));

        CopyRight.setForeground(new java.awt.Color(51, 51, 51));
        CopyRight.setText("Todos los derechos reservados - 2021 ©");
        getContentPane().add(CopyRight, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 520, 270, 20));

        Name_label.setText("Nombre");
        getContentPane().add(Name_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 60, 20));

        lastname_label1.setText("Primer Apellido");
        getContentPane().add(lastname_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 110, 20));

        lastname_label2.setText("Segundo Apellido");
        getContentPane().add(lastname_label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 110, 20));

        ID_label.setText("Cedula o ID");
        getContentPane().add(ID_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 110, 20));

        tel_label.setText("Telefono");
        getContentPane().add(tel_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 110, 20));

        Country_label.setText("Pais");
        getContentPane().add(Country_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 120, 20));

        age_label.setText("Edad");
        getContentPane().add(age_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 120, 20));

        txt_nombre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 204, 255), new java.awt.Color(51, 204, 255), null, new java.awt.Color(51, 204, 255)));
        txt_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreActionPerformed(evt);
            }
        });
        txt_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nombreKeyTyped(evt);
            }
        });
        getContentPane().add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 120, -1));

        txt_id.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 204, 255), new java.awt.Color(51, 204, 255), null, new java.awt.Color(51, 204, 255)));
        txt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idActionPerformed(evt);
            }
        });
        txt_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_idKeyTyped(evt);
            }
        });
        getContentPane().add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 120, -1));

        txt_ap1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 204, 255), new java.awt.Color(51, 204, 255), null, new java.awt.Color(51, 204, 255)));
        txt_ap1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ap1ActionPerformed(evt);
            }
        });
        txt_ap1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_ap1KeyTyped(evt);
            }
        });
        getContentPane().add(txt_ap1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 120, 20));

        txt_ap2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 204, 255), new java.awt.Color(51, 204, 255), null, new java.awt.Color(51, 204, 255)));
        txt_ap2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ap2ActionPerformed(evt);
            }
        });
        txt_ap2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_ap2KeyTyped(evt);
            }
        });
        getContentPane().add(txt_ap2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 120, -1));

        txt_telefono.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 204, 255), new java.awt.Color(51, 204, 255), null, new java.awt.Color(51, 204, 255)));
        txt_telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_telefonoActionPerformed(evt);
            }
        });
        txt_telefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_telefonoKeyTyped(evt);
            }
        });
        getContentPane().add(txt_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 120, -1));

        cb_pais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_paisActionPerformed(evt);
            }
        });
        getContentPane().add(cb_pais, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 120, -1));

        txt_edad.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 204, 255), new java.awt.Color(51, 204, 255), null, new java.awt.Color(51, 204, 255)));
        txt_edad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_edadActionPerformed(evt);
            }
        });
        txt_edad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_edadKeyTyped(evt);
            }
        });
        getContentPane().add(txt_edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 120, -1));

        btn_agregar1.setBackground(new java.awt.Color(102, 204, 255));
        btn_agregar1.setForeground(new java.awt.Color(255, 255, 255));
        btn_agregar1.setText("Agregar");
        btn_agregar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 204, 255), new java.awt.Color(51, 204, 255), java.awt.Color.white, new java.awt.Color(51, 204, 255)));
        btn_agregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_agregar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 460, 100, 30));

        btn_limpiar.setBackground(new java.awt.Color(102, 204, 255));
        btn_limpiar.setForeground(new java.awt.Color(255, 255, 255));
        btn_limpiar.setText("Limpiar Casillas");
        btn_limpiar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 204, 255), new java.awt.Color(51, 204, 255), java.awt.Color.white, new java.awt.Color(51, 204, 255)));
        btn_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 460, 100, 30));

        btn_borrar.setBackground(new java.awt.Color(102, 204, 255));
        btn_borrar.setForeground(new java.awt.Color(255, 255, 255));
        btn_borrar.setText("Borrar");
        btn_borrar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 204, 255), new java.awt.Color(51, 204, 255), java.awt.Color.white, new java.awt.Color(51, 204, 255)));
        btn_borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_borrarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_borrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 460, 100, 30));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/onu_scholarship_sys/1200px-Flag_of_the_United_Nations.svg.png"))); // NOI18N
        background.setText("Buscar");
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 550));

        txt_id2.setToolTipText("");
        txt_id2.setEnabled(false);
        getContentPane().add(txt_id2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_fnacimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_fnacimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_fnacimientoActionPerformed

    private void txt_universidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_universidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_universidadActionPerformed

    private void txt_correoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_correoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_correoActionPerformed

    private void Back_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_buttonActionPerformed
        this.dispose();
        call_menu();
    }//GEN-LAST:event_Back_buttonActionPerformed

    private void txt_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreActionPerformed
        this.txt_nombre.getText();
    }//GEN-LAST:event_txt_nombreActionPerformed

    private void txt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idActionPerformed
        this.txt_nombre.getText();
    }//GEN-LAST:event_txt_idActionPerformed

    private void txt_ap1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ap1ActionPerformed
        this.txt_nombre.getText();
    }//GEN-LAST:event_txt_ap1ActionPerformed

    private void txt_ap2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ap2ActionPerformed
        this.txt_nombre.getText();
    }//GEN-LAST:event_txt_ap2ActionPerformed

    private void txt_telefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_telefonoActionPerformed
        this.txt_nombre.getText();
    }//GEN-LAST:event_txt_telefonoActionPerformed

    private void txt_edadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_edadActionPerformed
        this.txt_nombre.getText();
    }//GEN-LAST:event_txt_edadActionPerformed

    private void txt_universidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_universidadKeyTyped
        char c = evt.getKeyChar();//se llama el evento
        if (Character.isDigit(c)) {//se identifica si se ingreso un numero
            evt.consume();//evita que el numero se guarde
            JOptionPane.showMessageDialog(null, "Favor solo digite caracteres alfabeticos", "CUIDADO", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_txt_universidadKeyTyped

    private void txt_correoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_correoKeyTyped
        char c = evt.getKeyChar();//se llama el evento
        if (Character.isDigit(c)) {//se identifica si se ingreso un numero
            evt.consume();//evita que el numero se guarde
            JOptionPane.showMessageDialog(null, "Favor solo digite caracteres alfabeticos", "CUIDADO", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_txt_correoKeyTyped

    private void txt_nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nombreKeyTyped
        char c = evt.getKeyChar();//se llama el evento
        if (Character.isDigit(c)) {//se identifica si se ingreso un numero
            evt.consume();//evita que el numero se guarde
            JOptionPane.showMessageDialog(null, "Favor solo digite caracteres alfabeticos", "CUIDADO", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_txt_nombreKeyTyped

    private void txt_ap1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ap1KeyTyped
        char c = evt.getKeyChar();//se llama el evento
        if (Character.isDigit(c)) {//se identifica si se ingreso un numero
            evt.consume();//evita que el numero se guarde
            JOptionPane.showMessageDialog(null, "Favor solo digite caracteres alfabeticos", "CUIDADO", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_txt_ap1KeyTyped

    private void txt_ap2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ap2KeyTyped
        char c = evt.getKeyChar();//se llama el evento
        if (Character.isDigit(c)) {//se identifica si se ingreso un numero
            evt.consume();//evita que el numero se guarde
            JOptionPane.showMessageDialog(null, "Favor solo digite caracteres alfabeticos", "CUIDADO", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_txt_ap2KeyTyped

    private void txt_edadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_edadKeyTyped
        char c = evt.getKeyChar();//se llama el evento
        if (Character.isLetter(c)) {//se identifica si se ingreso una letra
            evt.consume();//evita que se guarde la letra
            JOptionPane.showMessageDialog(null, "Favor solo digite caracteres numericos", "CUIDADO", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_txt_edadKeyTyped

    private void txt_telefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_telefonoKeyTyped
        char c = evt.getKeyChar();//se llama el evento
        if (Character.isLetter(c)) {//se identifica si se ingreso una letra
            evt.consume();//evita que se guarde la letra
            JOptionPane.showMessageDialog(null, "Favor solo digite caracteres numericos", "CUIDADO", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_txt_telefonoKeyTyped

    private void txt_idKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_idKeyTyped
        char c = evt.getKeyChar();//se llama el evento
        if (Character.isLetter(c)) {//se identifica si se ingreso una letra
            evt.consume();//evita que se guarde la letra
            JOptionPane.showMessageDialog(null, "Favor solo digite caracteres numericos", "CUIDADO", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_txt_idKeyTyped

    private void txt_fnacimientoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_fnacimientoKeyTyped
        char c = evt.getKeyChar();//se llama el evento
        if (Character.isLetter(c)) {//se identifica si se ingreso una letra
            evt.consume();//evita que se guarde la letra
            JOptionPane.showMessageDialog(null, "Favor solo digite caracteres numericos", "CUIDADO", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_txt_fnacimientoKeyTyped

    private void cb_estado_civilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_estado_civilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_estado_civilActionPerformed

    private void cb_carreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_carreraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_carreraActionPerformed

    private void cb_paisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_paisActionPerformed

    }//GEN-LAST:event_cb_paisActionPerformed

    private void txt_direccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_direccionKeyTyped
        char c = evt.getKeyChar();//se llama el evento
        if (Character.isDigit(c)) {//se identifica si se ingreso un numero
            evt.consume();//evita que el numero se guarde
            JOptionPane.showMessageDialog(null, "Favor solo digite caracteres alfabeticos", "CUIDADO", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_txt_direccionKeyTyped

    private void btn_agregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregar1ActionPerformed

        Connection con = null;

        try {

            con = getConnection();
            ps = con.prepareStatement("Insert into Estudiante (ID, Nombre, Apellido1, Apellido2, Carrera, Estado_Civil, Pais, Direccion, Fecha_Nacimiento, Edad, Universidad, Telefono, Correo_Electronico, Estado, Observaciones)"
                    + "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)");

            ps.setString(1, txt_id.getText());
            ps.setString(2, txt_nombre.getText());
            ps.setString(3, txt_ap1.getText());
            ps.setString(4, txt_ap2.getText());
            ps.setString(5, cb_carrera.getSelectedItem().toString());
            ps.setString(6, cb_estado_civil.getSelectedItem().toString());
            ps.setString(7, cb_pais.getSelectedItem().toString());
            ps.setString(8, txt_direccion.getText());
            ps.setString(9, txt_fnacimiento.getText());
            ps.setString(10, txt_edad.getText());
            ps.setString(11, txt_universidad.getText());
            ps.setString(12, txt_telefono.getText());
            ps.setString(13, txt_correo.getText());
            ps.setString(14, cb_estado.getSelectedItem().toString());
            ps.setString(15, txt_observaciones.getText());

            int res = ps.executeUpdate();
            if (res > 0) {
                JOptionPane.showMessageDialog(null, "Persona agregada correctamente.");
                limpiarcajas();
            } else {
                JOptionPane.showMessageDialog(null, "Error al guardar persona.");
                limpiarcajas();
            }

            con.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_btn_agregar1ActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        Connection con = null;

        try {
            con = getConnection();
            ps = con.prepareStatement("Select * from Estudiante Where id = ?");
            ps.setString(1, txt_id.getText());

            rs = ps.executeQuery();

            if (rs.next()) {
                txt_id.setText(rs.getString("ID"));
                txt_nombre.setText(rs.getString("Nombre"));
                txt_ap1.setText(rs.getString("Apellido1"));
                txt_ap2.setText(rs.getString("Apellido2"));
                cb_carrera.setSelectedItem(rs.getString("Carrera"));
                cb_estado_civil.setSelectedItem(rs.getString("Estado_Civil"));
                cb_pais.setSelectedItem(rs.getString("Pais"));
                txt_direccion.setText(rs.getString("Direccion"));
                txt_fnacimiento.setText(rs.getString("Fecha_Nacimiento"));
                txt_edad.setText(rs.getString("Edad"));
                txt_universidad.setText(rs.getString("Universidad"));
                txt_telefono.setText(rs.getString("Telefono"));
                txt_correo.setText(rs.getString("Correo_Electronico"));
                cb_estado.setSelectedItem(rs.getString("Estado"));
                txt_observaciones.setText(rs.getString("Observaciones"));

            } else {
                JOptionPane.showMessageDialog(null, "No hay registros en la base de datos con ese numero de ID");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        }
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarActionPerformed
        Connection con = null;

        try {

            con = getConnection();
            ps = con.prepareStatement("Update Estudiante Set ID = ?, Nombre = ?, Apellido1 = ?, Apellido2 = ?, Carrera = ?, Estado_Civil = ?, Pais = ?, Direccion = ?, Fecha_Nacimiento = ?, Edad = ?, Universidad = ?, Telefono = ?,  Correo_Electronico = ?, Estado = ?, Observaciones = ? Where ID = ?");

            ps.setString(1, txt_id.getText());
            ps.setString(2, txt_nombre.getText());
            ps.setString(3, txt_ap1.getText());
            ps.setString(4, txt_ap2.getText());
            ps.setString(5, cb_carrera.getSelectedItem().toString());
            ps.setString(6, cb_estado_civil.getSelectedItem().toString());
            ps.setString(7, cb_pais.getSelectedItem().toString());
            ps.setString(8, txt_direccion.getText());
            ps.setString(9, txt_fnacimiento.getText());
            ps.setString(10, txt_edad.getText());
            ps.setString(11, txt_universidad.getText());
            ps.setString(12, txt_telefono.getText());
            ps.setString(13, txt_correo.getText());
            ps.setString(14, cb_estado.getSelectedItem().toString());
            ps.setString(15, txt_observaciones.getText());
            ps.setString(16, txt_id.getText());

            int res = ps.executeUpdate();
            if (res > 0) {
                JOptionPane.showMessageDialog(null, "Persona modificada correctamente.");
                limpiarcajas();
            } else {
                JOptionPane.showMessageDialog(null, "Error al modificar persona.");
//                limpiarcajas();
            }

            con.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Error: " + e);
        }
    }//GEN-LAST:event_btn_modificarActionPerformed

    private void btn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarActionPerformed
        limpiarcajas();
    }//GEN-LAST:event_btn_limpiarActionPerformed

    private void btn_borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_borrarActionPerformed
        Connection con = null;

        try {

            con = getConnection();
            ps = con.prepareStatement("Delete from Estudiante Where ID = ?");

            ps.setInt(1, Integer.parseInt(txt_id.getText()));

            int res = ps.executeUpdate();
            if (res > 0) {
                JOptionPane.showMessageDialog(null, "Persona eliminada correctamente.");
                limpiarcajas();
            } else {
                JOptionPane.showMessageDialog(null, "Error al eliminar persona.");
                limpiarcajas();
            }

            con.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btn_borrarActionPerformed

    // declaracion de metodos para llamado de formularios
    public JSONArray poblar_lista_paises() throws IOException {

        Countries paises = new Countries();

        JSONArray array = paises.GetCountries();

        JSONObject object = null;

        if (array != null) {

            for (int i = 0; i < array.length(); i++) {

                object = array.getJSONObject(i);
                cb_pais.addItem(object.getString("name"));

            }
        }
        return array;
    }

    private void call_menu() {
        Main_Menu menu_principal = new Main_Menu();
        menu_principal.setTitle("Menu Principal");
        menu_principal.setSize(900, 600);
        menu_principal.setLocationRelativeTo(null);
        menu_principal.setVisible(true);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(New_Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(New_Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(New_Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(New_Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new New_Student().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(New_Student.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_button;
    private javax.swing.JLabel Civil_State_label;
    private javax.swing.JLabel Civil_State_label1;
    private javax.swing.JLabel CopyRight;
    private javax.swing.JLabel Country_label;
    private javax.swing.JLabel ID_label;
    private javax.swing.JLabel Major_label;
    private javax.swing.JLabel Name_label;
    private javax.swing.JSeparator Separator_1;
    private javax.swing.JSeparator Separator_2;
    private javax.swing.JLabel address_label;
    private javax.swing.JLabel age_label;
    private javax.swing.JLabel background;
    private javax.swing.JButton btn_agregar1;
    private javax.swing.JButton btn_borrar;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_limpiar;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JComboBox<String> cb_carrera;
    private javax.swing.JComboBox<String> cb_estado;
    private javax.swing.JComboBox<String> cb_estado_civil;
    private javax.swing.JComboBox<Object> cb_pais;
    private javax.swing.JLabel college_label;
    private javax.swing.JLabel current_state_label;
    private javax.swing.JLabel email_label;
    private javax.swing.JLabel est_reg_label;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lastname_label1;
    private javax.swing.JLabel lastname_label2;
    private javax.swing.JLabel observations_label;
    private javax.swing.JLabel tel_label;
    private javax.swing.JTextField txt_ap1;
    private javax.swing.JTextField txt_ap2;
    private javax.swing.JTextField txt_correo;
    private javax.swing.JTextArea txt_direccion;
    private javax.swing.JTextField txt_edad;
    private javax.swing.JTextField txt_fnacimiento;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_id2;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextArea txt_observaciones;
    private javax.swing.JTextField txt_telefono;
    private javax.swing.JTextField txt_universidad;
    // End of variables declaration//GEN-END:variables
}
